### ISSUE TITLE
Change batch_size size

### ISSUE THREAD

**Issue by yyqxnice** [iffiX/PGPPortfolio-pytorch#4]
Hello, I found that the batch_size is very large during the operation. I adjusted it down in the config but the first dimension of the matrix is still large and changing. Do you have any solutions? How do I change the first dimension of the matrix? ?

**Comment by iffiX** [comment]
Hi, which matrix at what point of the program execution are you referring to? 

batch_size controls the number of time steps used in a single training step, but does not affect the number of test time steps used in the `training_step_end` method @ https://github.com/iffiX/PGPortfolio-pytorch/blob/c87205beec838aff4c98d83cb2df9b1d8c3f0d3c/pgportfolio/nnagent/tradertrainer.py#L90, which is the evaluation step for logging metrics, the number of test time steps is affected by "test_portion" and "validation_portion" in config.

**Comment by yyqxnice** [comment]
> Hi, which matrix at what point of the program execution are you referring to?
> 
> batch_size controls the number of time steps used in a single training step, but does not affect the number of test time steps used in the `training_step_end` method @
> 
> https://github.com/iffiX/PGPortfolio-pytorch/blob/c87205beec838aff4c98d83cb2df9b1d8c3f0d3c/pgportfolio/nnagent/tradertrainer.py#L90
> 
> , which is the evaluation step for logging metrics, the number of test time steps is affected by "test_portion" and "validation_portion" in config.

Hello, (1) When I execute data to network.py for the first time, the matrix dimension is [109,3,11,31], but the matrix dimension is [2760, 3，11，31],when I execute network.py for the second time, I want to know why there is such a change in the first dimension, how can I reduce the first dimension? Hope to get your answer. (2) I have a new question again, what is the whole replay_buffer doing, what is the _train_idx in the middle, I tried to modify the first dimension of the matrix by changing the replay_buffer but something went wrong.

**Comment by iffiX** [comment]
### For question 1
Hi, as I have explained in the previous response, the `[109,3,11,31]` shape is produced by the training step, where a fixed-size window of features (`batch["X"]`) and operations (represented by **w** eights of portfolios, `batch["last_w"]` and `new_w`) is fed into the network.
```
    def training_step(self, batch, _batch_idx):
        batch = batch[0]
        print(batch["X"].shape)                               # you can see [109,3,11,31] from here
        new_w = self._net(batch["X"], batch["last_w"])
        batch["setw"](new_w[:, 1:])
        return self._init_metrics()\
            .eval(batch["y"], batch["last_w"], new_w).loss
```
the `[2760, 3，11，31]` is produced by feeding the testing portion of **pvm** (explained below) into the network:
```
    def training_step_end(self, training_output):
        # Manually test after each training step.
        # Note: _test_set_X, _test_set_y, etc. are registered buffers.
        fast_train = self._train_config["fast_train"] 

        self._net.eval()
        print(self._test_set_X.shape)                  # you can see [2760,3,11,31] from here
        new_w = self._net(self._test_set_X, self._test_set_last_w)
        self._test_set_setw(new_w[:, 1:])
```
The size of the testing portion is controlled by the `test_portion` subfield of the `input` field in your configuration, it is also affected by your start/end date (2015/05/01, 2017/04/27) and period length (1800 sec) between data points. 
```
    "input": {
        "coin_number": 11,
        "end_date": "2017/04/27",
        "fake_ratio": 1,
        "feature_number": 3,
        "global_period": 1800,
        "market": "poloniex",
        "norm_method": "absolute",
        "portion_reversed": false,
        "save_memory_mode": false,
        "start_date": "2015/05/01",
        "test_portion": 0.08,                     < adjust it down to get a smaller testing batch size 
        "validation_portion": 0,
        "volume_average_days": 30,
        "window_size": 31
    },
```
In general, the batch size 2760 is **required** because you want a wide range of testing data so your metrics would be accurate. The testing part also **must be kept** there because the framework is using its logged metrics to achieve early-stopping in training, etc. If your hardware does not allow you to deal with data of size bigger than [2760,3,11,31], the best way is using cpu (MUCH SLOWER!) by using option `--device=cpu` in your command line, or using a better accelerator.

### For question 2
The function of the replay buffer (portfolio vector memory, short for **pvm**) is explained in this figure from the original paper:
![replay buffer](https://github.com/iffiX/PGPortfolio-pytorch/raw/master/images/agent.png)
The name "replay buffer" is used instead because it is a common name used in reinforcement learning literature and **pvm** serves the same function with some minor differences. You should not modify the size of **pvm** since it stores the whole history.

"_train_idx" is short for "train entry index", and its content is produced by this method call:
```
self._train_idx, self._test_idx, self._val_idx = \
            self._divide_data(period_num, window_size, test_portion,
                              validation_portion, portion_reversed)
``` 
Which has the following docstring:
```
"""
Divide training data into three portions, train, test and validation.

Args:
    period_num: Number of price records in the time dimension.
    window_size: Sliding window size of history price records
    visible to the agent.
    test_portion/val_portion: Percent of these two portions.
    portion_reversed: Whether reverse the order of portions.

Returns:
    Three np.ndarray type index arrays, train, test, validation.
"""
```
The indexes means which positions of the *pvm* are used for training, testing, validation, etc, and they are contiguous integer arrays like `[0, 1, 2, 3, ....]`, I think the docstring should be sufficient to explain their content and usage.
