### ISSUE TITLE
About requirements

### ISSUE THREAD

**Issue by yyqxnice** [iffiX/PGPPortfolio-pytorch#7]
[requirements.txt](https://github.com/iffiX/PGPortfolio-pytorch/files/6950382/requirements.txt)
I tried to run this program on **rtx3090**, but the environment mismatch restricted my operation. First of all, pandas only supports panel function **0.23.4** and below. Secondly, I am **cuda 11.1** and only support **pytorch 1.8.1** and above. The above is my modified **requirements.txt** for **cuda10.2**, if I want to run this program on cuda11.1, not only need to change the pytorch version to 1.8.1, but also need to change other environment versions (I haven’t tried this part yet. ). (1) I tried to search for how to replace the panel function on the Internet but did not find any useful results. (2) I'm wondering if I can't draw a line chart, will it be the version of matplotlib that I have modified.

**Comment by yyqxnice** [comment]
Thank you very much for your previous answers to my question.I sliced and changed it, but my batch_size size can only be set to **5 at most**, which is too slow. I need to run for **more than an hour for an epoch**, so I try to find other solutions , Such as put into rtx3090 to run.

**Comment by iffiX** [comment]
Hi, the new requirements.txt works fine, since the framework is rewritten from their original implementation [here](https://github.com/ZhengyaoJiang/PGPortfolio), and PyTorch >= 1.5.0 will work without any problem. I just used the search function of Github and the "ag" [command](https://github.com/ggreer/the_silver_searcher) to confirm that all panel functions from pandas are completely removed and replaced with DataFrame, which is also one of our main modifications. Shows no result. So I am not sure which line in which file you are referring to. 

You should also be able to draw line charts without any problems using your matplotlib version.

Also for the batch_size problem, I still cannot reproduce your problem on my side, with your new requirements.txt, with a normal batch size = 109 (the number of time points used to operate), and on my laptop, even a modest i7-6700hq CPU can train 30~40 iterations per second, GTX970m GPU can train 90 iterations per second and only consumes 548 MB GPU memory. An epoch containing 1000 steps normally takes 20 seconds on my laptop and less than 10 seconds on cluster V100 GPUs. I can only say that it's probably some special problem on your side as I cannot reproduce your problem with your environment configuration and config file. (There is one problem in your configuration file, I have mentioned that in your previous issue, and the corrected version works fine)

Therefore, I encourage you to work from the ground up and find where the real problem occurs, our README should contain enough information to allow you to understand how this rewritten version is organized and how data flows in different modules. 

Finally, I apologize for not being able to help you further on this due to the limitation in time on my side, so I probably will archive this repository and accept no more issues, sorry for that again, I wish you find the problem or create a new implementation on your own successfully.
